<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="149" started-at="2019-12-08T06:06:32Z" finished-at="2019-12-08T06:06:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="149" started-at="2019-12-08T06:06:32Z" finished-at="2019-12-08T06:06:32Z">
      <class name="seleniumdaysixpakage.loggingClass">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:seleniumdaysixpakage.loggingClass@4f933fd1]" name="beforeTest" is-config="true" duration-ms="30" started-at="2019-12-08T06:06:32Z" finished-at="2019-12-08T06:06:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="successMethod()[pri:0, instance:seleniumdaysixpakage.loggingClass@4f933fd1]" name="successMethod" duration-ms="15" started-at="2019-12-08T06:06:32Z" finished-at="2019-12-08T06:06:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successMethod -->
        <test-method status="FAIL" signature="failureMethod()[pri:1, instance:seleniumdaysixpakage.loggingClass@4f933fd1]" name="failureMethod" duration-ms="8" started-at="2019-12-08T06:06:32Z" finished-at="2019-12-08T06:06:32Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at seleniumdaysixpakage.loggingClass.failureMethod(loggingClass.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failureMethod -->
        <test-method status="SKIP" signature="skipMethod()[pri:0, instance:seleniumdaysixpakage.loggingClass@4f933fd1]" name="skipMethod" duration-ms="0" started-at="2019-12-08T06:06:32Z" depends-on-methods="seleniumdaysixpakage.loggingClass.failureMethod" finished-at="2019-12-08T06:06:32Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method loggingClass.skipMethod()[pri:0, instance:seleniumdaysixpakage.loggingClass@4f933fd1] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method loggingClass.skipMethod()[pri:0, instance:seleniumdaysixpakage.loggingClass@4f933fd1] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- skipMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:seleniumdaysixpakage.loggingClass@4f933fd1]" name="afterTest" is-config="true" duration-ms="1" started-at="2019-12-08T06:06:32Z" finished-at="2019-12-08T06:06:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- seleniumdaysixpakage.loggingClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
